---
- name: Install debian
  block:
    - name: disable ufw
      package:
          name: ufw
          state: absent

    - name: install firewalld
      package:
          name: firewalld
          state: present

    - name: config firewalld
      include_tasks: config.yml
  when: ansible_os_family == "Debian"