---
- name: Install debian
  block:
    - name: setup debian
      include_tasks: debian.yml
      when: firewalld_debian_enabled

    - name: setup redhat
      include_tasks: redhat.yml
  when: firewalld_enabled
