---
- name: setup debian
  include_tasks: debian.yml

- name: setup redhat
  include_tasks: redhat.yml

- name: config firewalld
  include_tasks: config.yml

- name: setup services
  include_tasks: service.yml
