---
- name: Install redhat
  block:
    - name: install firewalld
      package:
          name: firewalld
          state: present

    - name: config firewalld
      include_tasks: config.yml
  when: ansible_os_family == "RedHat"